spring.application.name=authDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=Yakubu2020

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret-key=b9b43eb1e0293b92f428e003b896d3156d4aa1bfa0aace42bb663abe930b2852
security.jwt.expiration-time=3600000
