spring.application.name=authDemo

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=Yakubu2020

spring.jpa.hibernate.ddl-auto=update
